### ISSUE TITLE
High Contrast not working

### ISSUE THREAD

**Issue by manorassaf** [pojome/one-click-accessibility#52] opened 2020-12-20 23:30 UTC
Hello,
When clicking on the High Contrast button - the screen turns black, but the text doesn't appear in yellow. Resulting in no text at all being showed.

You can see this issue in my site:
www.AssafManor.co.il

**Comment by arielk** [comment] 2021-03-24 09:15
Duplicate of #39

**Closed by arielk** 2021-03-24 09:15 UTC
